import React, { useEffect, useState } from 'react';
import api from '../../api/axios';
import SolarSystemScene from './SolarSystemScene';
import TimelineControls from './TimelineControls';
import AsteroidDetailsPanel from './AsteroidDetailsPanel';

export default function Simulation() {
  const [asteroids, setAsteroids] = useState([]); const [selectedAsteroidId, setSelectedAsteroidId] = useState('');
  const [simulationData, setSimulationData] = useState(null); const [listLoading, setListLoading] = useState(true); const [loading, setLoading] = useState(false); const [error, setError] = useState(null);
  const [currentTimeIndex, setCurrentTimeIndex] = useState(0); const [playing, setPlaying] = useState(false); const [speed, setSpeed] = useState(1);
  useEffect(() => { let active = true; api.get('/asteroids').then(({ data }) => { if (!active) return; const records = Array.isArray(data) ? data : []; setAsteroids(records); setSelectedAsteroidId(records[0]?.id || ''); }).catch(() => active && setError('Failed to fetch asteroid list.')).finally(() => active && setListLoading(false)); return () => { active = false; }; }, []);
  useEffect(() => { if (!selectedAsteroidId) { setSimulationData(null); return; } let active = true; setLoading(true); setError(null); setSimulationData(null); setCurrentTimeIndex(0); setPlaying(false); api.get(`/asteroids/${selectedAsteroidId}/simulation`).then(({ data }) => { if (active) setSimulationData(data); }).catch(() => active && setError('Failed to fetch simulation data. The asteroid may not have trajectory data available.')).finally(() => active && setLoading(false)); return () => { active = false; }; }, [selectedAsteroidId]);
  const points = simulationData?.trajectory?.points || [];
  useEffect(() => { if (!playing || points.length < 2) return undefined; const timer = window.setInterval(() => setCurrentTimeIndex((index) => { const next = index + 1; if (next >= points.length) { setPlaying(false); return points.length - 1; } return next; }), Math.max(40, 700 / speed)); return () => window.clearInterval(timer); }, [playing, points.length, speed]);
  if (listLoading) return <div className="simulation-loading"><h2>Simulation</h2><div className="loading-spinner" /></div>;
  return <div className="simulation-container"><header className="simulation-header"><h2>Simulation</h2><label>Select Asteroid:<select aria-label="Select asteroid" value={selectedAsteroidId} onChange={(event) => setSelectedAsteroidId(event.target.value)} disabled={loading}><option value="">-- Choose an asteroid --</option>{asteroids.map((asteroid) => <option key={asteroid.id} value={asteroid.id}>{asteroid.name} ({asteroid.id}) - Risk: {asteroid.custom_risk_score}</option>)}</select></label></header>{error && <div className="error-boundary">{error}</div>}{loading && <div className="simulation-loading"><div className="loading-spinner" /></div>}{!loading && simulationData && <div className="simulation-body"><div className="simulation-visual"><SolarSystemScene trajectoryPoints={points} currentTimeIndex={currentTimeIndex} onAsteroidSelect={() => setPlaying(false)} /></div><aside className="simulation-details"><TimelineControls trajectoryPoints={points} currentTimeIndex={currentTimeIndex} playing={playing} speed={speed} onSeek={setCurrentTimeIndex} onPlayPause={() => setPlaying((value) => !value)} onReset={() => { setPlaying(false); setCurrentTimeIndex(0); }} onSpeedChange={setSpeed} /><AsteroidDetailsPanel asteroid={simulationData.asteroid} trajectory={simulationData.trajectory} impactRisk={simulationData.impact_risk} orbitalElements={simulationData.orbital_elements} closeApproaches={simulationData.close_approaches || []} /></aside></div>}{!loading && !error && selectedAsteroidId && !simulationData && <p className="simulation-empty">No simulation data available for this asteroid.</p>}<footer className="simulation-disclaimer">AstraGuard visualizes publicly available NASA/JPL data and provides application-derived analytics. It is not an official planetary-defense warning system.</footer></div>;
}
